// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DvdRental.Server.Models;

public partial class actor
{
    public int actor_id { get; set; }

    public string first_name { get; set; }

    public string last_name { get; set; }

    public DateTime last_update { get; set; }

    public virtual ICollection<film_actor> film_actors { get; set; } = new List<film_actor>();
}