// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DvdRental.Server.Models;

public partial class category
{
    public int category_id { get; set; }

    public string name { get; set; }

    public DateTime last_update { get; set; }

    public virtual ICollection<film_category> film_categories { get; set; } = new List<film_category>();
}