// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DvdRental.Server.Models;

public partial class film
{
    public int film_id { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public int? release_year { get; set; }

    public short language_id { get; set; }

    public short rental_duration { get; set; }

    public decimal? rental_rate { get; set; }

    public short? length { get; set; }

    public decimal? replacement_cost { get; set; }

    public string rating { get; set; }

    public DateTime last_update { get; set; }

    public string special_features { get; set; }

    public string fulltext { get; set; }

    public virtual ICollection<film_actor> film_actors { get; set; } = new List<film_actor>();

    public virtual film_category film_category { get; set; }
}