// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DvdRental.Server.Models;

public partial class film_category
{
    public int film_id { get; set; }

    public int category_id { get; set; }

    public DateTime last_update { get; set; }

    public virtual category category { get; set; }

    public virtual film film { get; set; }
}